enum {
	EARS_POINTY = 1,
	EARS_ROUND,
	EARS_ROUND_LONG,
	
	NOSE_BIG_ROUND,
	NOSE_SMALL_FLAT,
	NOSE_BIG_FLAT,
	
	HAIR_SPOTS_BIG,
	HAIR_SPOTS_SMALL,
	HAIR_SPOTS_HEARTS,
	
	HAIR_SPOTS_COLOR_BLOND,
	HAIR_SPOTS_COLOR_WHITE,
	HAIR_SPOTS_COLOR_BROWN,
	HAIR_SPOTS_COLOR_BLACK,
	HAIR_SPOTS_COLOR_GREY,
	
	HAIR_COLOR_BLOND,
	HAIR_COLOR_WHITE,
	HAIR_COLOR_GREY,
	HAIR_COLOR_BROWN,
	HAIR_COLOR_BLACK,
	
	NOSE_SMALL,
	NOSE_ROUND,
	NOSE_NARROW,
	NOSE_TALL,
	
	EYES_SMALL,
	EYES_CLOSED,
	EYES_COMMON,
	EYES_EYEPATCH
}

static func describe(element: int) -> String:
	match element:
		EARS_POINTY: return "DESCRIPTION_EARS_POINTY"
		EARS_ROUND: return "DESCRIPTION_EARS_DROOPY_SMALL"
		EARS_ROUND_LONG: return "DESCRIPTION_EARS_DROOPY_BIG"
		
		NOSE_BIG_ROUND: return "DESCRIPTION_NOSE_BIG_ROUND"
		NOSE_ROUND: return "DESCRIPTION_NOSE_ROUND"
		NOSE_SMALL_FLAT: return "DESCRIPTION_NOSE_SMALL_FLAT"
		NOSE_BIG_FLAT: return "DESCRIPTION_NOSE_BIG_FLAT"
		NOSE_NARROW: return "DESCRIPTION_NOSE_NARROW"
		
		HAIR_SPOTS_BIG: return "DESCRIPTION_SPOTS_BIG"
		HAIR_SPOTS_SMALL: return "DESCRIPTION_SPOTS_SMALL"
		HAIR_SPOTS_HEARTS: return "DESCRIPTION_SPOTS_HEARTS"
		
		HAIR_COLOR_BLACK: return "DESCRIPTION_FUR_BLACK"
		HAIR_COLOR_BLOND: return "DESCRIPTION_FUR_BLOND"
		HAIR_COLOR_BROWN: return "DESCRIPTION_FUR_BROWN"
		HAIR_COLOR_WHITE: return "DESCRIPTION_FUR_WHITE"
		HAIR_COLOR_GREY: return "DESCRIPTION_FUR_GREY"
		
		HAIR_SPOTS_COLOR_GREY: return "DESCRIPTION_SPOTS_GREY"
		HAIR_SPOTS_COLOR_WHITE: return "DESCRIPTION_SPOTS_WHITE"
		HAIR_SPOTS_COLOR_BROWN: return "DESCRIPTION_SPOTS_BROWN"
		HAIR_SPOTS_COLOR_BLOND:  return "DESCRIPTION_SPOTS_BLOND"
		HAIR_SPOTS_COLOR_BLACK: return "DESCRIPTION_SPOTS_BLACK"

		EYES_COMMON: return "DESCRIPTION_EYES_COMMON"
		EYES_EYEPATCH: return "DESCRIPTION_EYES_EYEPATCH"
	
	return "Unknown"
